variable "kubeconfig_path" {
  description = "Path to the kubeconfig file generated by the infra layer"
  type        = string
  default     = "../00-infra/kubeconfig"
}

variable "nfs_server" {
  description = "NFS server IP address"
  type        = string
}

variable "nfs_path" {
  description = "NFS export path — the provisioner creates a subdirectory per PVC under this path"
  type        = string
}
